#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

pushd .
cd $(dirname $0)
cd ../_lib/picom
git reset --hard
git clean -fdx
git submodule update --init --recursive
command -v ninja &> /dev/null || { pip3 install --user ninja; hash -r; }
command -v meson &> /dev/null || { pip3 install --user meson; hash -r; }
export C_INCLUDE_PATH=~/.root/include
meson --buildtype=release . build
meson configure -Dprefix=$HOME/.root build
ninja -C build install
popd

