#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

TMPDIR=$(mktemp -d)

cd $TMPDIR

cleanup () {
    rm -rf $TMPDIR
}

trap cleanup EXIT

VERSION=6.6.14

wget https://ftp.gnu.org/pub/gnu/global/global-${VERSION}.tar.gz
tar -xzvf global-${VERSION}.tar.gz
cd global-${VERSION}
./configure --prefix ~/.local --with-exuberant-ctags=/usr/bin/ctags
make && make install

