#!/usr/bin/env bash

set -e
set -x

VERSION=6.5.7

wget https://ftp.gnu.org/pub/gnu/global/global-${VERSION}.tar.gz
tar -xzvf global-${VERSION}.tar.gz
cd global-${VERSION}
./configure --prefix ~/.root --with-exuberant-ctags=/usr/bin/ctags
make && make install
cd ..
rm -rf global-${VERSION}.tar.gz global-${VERSION}

