#!/bin/bash

input=$(cat)
cwd=$(echo "$input" | jq -r '.workspace.current_dir')
user=$(whoami)
host=$(hostname -s)
git_info=$(cd "$cwd" 2>/dev/null && git rev-parse --abbrev-ref HEAD 2>/dev/null | sed 's/.*/git:(\0)/')
printf "\033[1;32m%s@%s:\033[0;36m%s\033[1;34m%s\033[0m" "$user" "$host" "$cwd" "${git_info:+ $git_info}"
