#!/usr/bin/env bash

set -e
set -u
set -x

pushd .
cd $(dirname $0)
cd ../_lib/_opt/alpine
git reset --hard
git clean -fdx
./configure --prefix ~/.local --with-passfile=.pine-passfile
make && make install
popd

