#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

TMPDIR=$(mktemp -d)

cd $TMPDIR

cleanup () {
    rm -rf $TMPDIR
}

trap cleanup EXIT

VERSION=3.8.4

wget https://archive.apache.org/dist/maven/maven-3/$VERSION/binaries/apache-maven-${VERSION}-bin.tar.gz
tar -xzvf apache-maven-${VERSION}-bin.tar.gz
mkdir -p ~/.root/var
mv apache-maven-${VERSION} ~/.root/var/

