#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

TMPDIR=$(mktemp -d)

cd $TMPDIR

cleanup () {
    rm -rf $TMPDIR
}

trap cleanup EXIT

VERSION=3.9.10

wget https://archive.apache.org/dist/maven/maven-3/$VERSION/binaries/apache-maven-${VERSION}-bin.tar.gz
tar -xzvf apache-maven-${VERSION}-bin.tar.gz
mkdir -p ~/.local/var
rm -rf ~/.local/var/apache-maven-${VERSION}
mv apache-maven-${VERSION} ~/.local/var/
ln -sf ~/.local/var/apache-maven-${VERSION}/bin/mvn ~/.dotfiles/_bin/mvn

