#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

pushd .
cd $(dirname $0)
cd ../_lib/xclip
git reset --hard
git clean -fdx
[ ! -f ./configure ] && autoreconf
./configure --prefix ~/.root
make && make install
popd

