[settings]
auto_install = false
disable_tools = ["poetry", "python"]
experimental = false
locked = false
lockfile = true
paranoid = true

[tools]
ag = "2.2.0"
awscli = { version = "2.34.24", symlink_bins = "true" }
cmake = "4.3.1"
codex = "latest"
fzf = "0.71.0"
maven = "3.9.15"
neovim = "0.12.1"
ninja = "1.13.2"
ollama = "latest"
pandoc = "3.9.0.2"
perl = "5.42.2"
pre-commit = "4.5.1"
ripgrep = "15.1.0"
rust = "latest"
shellcheck = "0.11.0"
terraform = "1.7.4"
tflint = "0.61.0"
vim = "9.2.0361"
#terraform-docs = "system"
#terraformer = "system"
#terragrunt = "system"
#tflint = "system"
#tfupdate = "system"
yamllint = "1.38.0"
