#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

TMPDIR=$(mktemp -d)

cd $TMPDIR

cleanup () {
    rm -rf $TMPDIR
}

trap cleanup EXIT

if [[ ! $(uname -o) =~ .*Linux ]]; then
    echo "Only Linux is supported" >&2
    exit 1
fi

ARCH=$(uname -m | sed s/aarch64/arm64/g | sed s/x86_64/x64/g)
VERSION="2026.4.5"

CURRENT=$(
    command -v mise &> /dev/null && {
        mise version -q -J | \
        jq -r '.version' | \
        cut -d ' ' -f 1;
    } ||
    echo "0"
)

if [[ $CURRENT == $VERSION ]]; then
    exit 0
fi

curl -L -O https://github.com/jdx/mise/releases/download/v${VERSION}/mise-v${VERSION}-linux-${ARCH}.tar.gz
tar -xzvf mise-v${VERSION}-linux-${ARCH}.tar.gz
mkdir -p ~/.local/bin
cp -p mise/bin/mise ~/.local/bin
rsync -a mise/man/ ~/.local/share/man/

export PATH=~/.local/bin:$PATH

mise install

