#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

TMPDIR=$(mktemp -d)

cd $TMPDIR

cleanup () {
    rm -rf $TMPDIR
}

trap cleanup EXIT

case $(uname -s) in
    Linux)  PLATFORM=linux ;;
    Darwin) PLATFORM=macos ;;
    *)
        echo "Unsupported OS: $(uname -s)" >&2
        exit 1
        ;;
esac

ARCH=$(uname -m | sed s/aarch64/arm64/g | sed s/x86_64/x64/g)
VERSION="2026.4.5"

CURRENT=$(
    [[ -x ~/.local/bin/mise ]] && {
        ~/.local/bin/mise version -q -J | \
        jq -r '.version' | \
        cut -d ' ' -f 1;
    } ||
    echo "0"
)

mise_trust_and_install () {
    cd ~
    ~/.local/bin/mise trust ~/.config/mise/config.toml
    if [[ -f ~/.mise.toml ]]; then
        ~/.local/bin/mise trust ~/.mise.toml
    fi
    ~/.local/bin/mise install
}

if [[ $CURRENT == $VERSION ]]; then
    mise_trust_and_install
    exit 0
fi

curl -L -O https://github.com/jdx/mise/releases/download/v${VERSION}/mise-v${VERSION}-${PLATFORM}-${ARCH}.tar.gz
tar -xzvf mise-v${VERSION}-${PLATFORM}-${ARCH}.tar.gz
mkdir -p ~/.local/bin
cp -p mise/bin/mise ~/.local/bin
rsync -a mise/man/ ~/.local/share/man/

mise_trust_and_install

