#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

if command -v gmake &> /dev/null; then
    MAKE=gmake
else
    MAKE=make
fi

export MAKE

pushd .
cd $(dirname $0)
cd ../_lib/_opt/bup
git reset --hard
git clean -fdx
# the environment needs to be free of any other tools for bup to build clean
export PATH=/bin:/usr/bin
export LD_LIBRARY_PATH=
export CFLAGS="-Wno-error"
# BUP_PYTHON_CONFIG, PKG_CONFIG_PATH are also other build-influencing
# variables
./configure --prefix ~/.local
$MAKE PREFIX=$HOME/.local
$MAKE PREFIX=$HOME/.local install
$MAKE test
popd

