#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

if command -v gmake &> /dev/null; then
    MAKE=gmake
else
    MAKE=make
fi

export MAKE

pushd .
cd $(dirname $0)
cd ../_lib/_opt/bup
git reset --hard
git clean -fdx
./configure
$MAKE PREFIX=$HOME/.root && \
    $MAKE PREFIX=$HOME/.root install
popd

