#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

if command -v gmake &> /dev/null; then
    MAKE=gmake
else
    MAKE=make
fi

pushd .
cd $(dirname $0)
cd ../_lib/bup
git reset --hard
git clean -fdx
./configure
$MAKE PREFIX=~/.root && $MAKE PREFIX=~/.root install
popd

