#!/usr/bin/env python
# vim: set et sw=4 ts=4:

# TODO make this work on FreeBSD

import argparse
from math import ceil
import subprocess
import sys

import x_usage

command = 'acpi -ab'

args = x_usage.parse_args()

returncode, stdout, stderr = x_usage.exec_command(args, command)

stdout = stdout.strip()

plugged = None
discharging = None
percent = None
time = None

for line in stdout.splitlines():
    if line.startswith('Adapter 0:'):
        plugged = 'off-line' not in line
    elif line.startswith('Battery 0:'):
        discharging = 'discharging' in line.lower()
        _, percent, time = line.split(',')
        percent = percent.strip()
        percent = int(percent.split('%')[0])
        time = time.strip()
        time = time.split(' ')[0]
    else:
        raise ValueError('unrecognized line')

assert percent is not None
assert plugged is not None
assert not (plugged and discharging)

x_usage.output(args,
               value=percent,
               format_string_default='{status} {percent}% {time}',
               format_string_i3='{status} {percent}% {time}',
               status='on' if not plugged else 'off',
               percent=percent,
               time=time,
               inverse=True)

