#!/usr/bin/env python
# vim: set et sw=4 ts=4:

# TODO make this work on FreeBSD

import argparse
from math import ceil
import subprocess
import sys

import x_usage

command = "mpstat 2 1 | grep Average: | awk '{ print (100 - $12) }'",

args = x_usage.parse_args()

returncode, stdout, stderr = x_usage.exec_command(args, command)

used_percent = float(stdout.strip())

x_usage.output(args,
               value=used_percent,
               format_string_default='{value:.2f}',
               format_string_i3='{value:03.0f}%')

