#!/usr/bin/env bash
# vim: set et sw=4 ts=4:

set -e
set -u

if command -v gdate &> /dev/null; then
    DATE=gdate
else
    DATE=date
fi

epoch=
precision=
utc=true

argv=$(getopt \
         -o 'e:lp:u' \
         -l 'epoch:' \
         -l 'local' \
         -l 'precision:' \
         -l 'utc' \
         -- \
         "$@")

eval set -- "$argv"

while true; do
    case "$1" in
        -e|--epoch)
            epoch=$2
            shift 2
            ;;
        -l|--local)
            utc=false
            shift
            ;;
        -p|--precision)
            precision=$2
            shift 2
            ;;
        -u|--utc)
            utc=true
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

if [[ -n $epoch ]]; then
    precision=${precision:-seconds}
else
    precision=${precision:-ns}
fi

$DATE \
    --iso-8601=$precision \
    $([[ -n $epoch ]] && echo "-d @$epoch") \
    $($utc && echo '-u') | \
        sed -e 's/+00:\{0,1\}00$/Z/g' | \
        sed -e 's/\([+-]\)\(..\):\(..\)/\1\2\3/g'

