#!/usr/bin/env python
# vim: et sw=4 ts=4:

import os
import subprocess
import sys

def heading(s):
    print '\033[31m[*] %s\033[0m' % s

def step(s):
    print '\033[33m[+] %s\033[0m' % s

def relink(target, linkname):
    target = os.path.expanduser(target)
    linkname = os.path.expanduser(linkname)
    if os.path.exists(linkname):
        if os.path.islink(linkname):
            os.unlink(linkname)
        else:
            raise Exception('%s is not a symlink' % linkname)
    os.symlink(target, linkname)

def unlink(p):
    try:
        os.unlink(os.path.expanuser(p))
    except:
        pass

def mkdir(p):
    try:
        os.makedirs(os.path.expanduser(p))
    except:
        pass

def run(p):
    try:
        subprocess.check_call(p, shell=True)
    except:
        raise

def main():
    # <top level mkdirs>

    heading('<dirs>')
    mkdir('~/.confmig')
    mkdir('~/.fonts')
    mkdir('~/.root')

    # <fonts>

    heading('<fonts>')
    mkdir('~/.fonts/adobe-fonts')
    relink('~/.dotfiles/_lib/source-code-pro', '~/.fonts/adobe-fonts/source-code-pro')
    os.system('fc-cache -f -v ~/.fonts/adobe-fonts/source-code-pro > /dev/null 2>&1')

    # alpine

    heading('alpine')
    step('remember to run alpine/install')

    # ansifilter

    heading('ansifilter')
    step('remember to run ansifilter/install')

    # bash

    heading('bash')
    relink('.dotfiles/bash/bashrc', '~/.bashrc')
    relink('.dotfiles/bash/bash_profile', '~/.bash_profile')

    # bup

    heading('bup')
    step('remember to run bup/install')

    # compton

    heading('compton')
    step('remember to run compton/install')

    # emacs

    heading('emacs')
    step('remember to run emacs/install-* (pick one)')
    step('<sometimes, emacs pdumper needs cmake and poppler installed>')

    # flake8

    heading('flake8')
    relink('~/.dotfiles/flake8/flake8', '~/.config/flake8')

    # fzf

    heading('fzf')
    step('remember to run fzf/install')

    # gdb

    heading('gdb')
    relink('.dotfiles/gdb/gdbinit', '~/.gdbinit')

    # git

    heading('git')
    relink('.dotfiles/git/gitconfig', '~/.gitconfig')

    # global

    heading('global')
    step('remember to run global/install')

    # gnome

    heading('gnome')
    step('remember to run gnome/load')

    # i3

    heading('i3')
    relink('.dotfiles/i3', '~/.i3')
    relink('.dotfiles/i3/i3blocks.conf', '~/.i3blocks.conf')
    # TODO i3lock systemd

    # iftop

    heading('iftop')
    relink('.dotfiles/iftop/iftoprc', '~/.iftoprc')

    # less

    heading('less')
    # ... sourced in shell/shellinteractive

    # maven

    heading('maven')
    step('remember to run maven/install')

    # mosh

    heading('mosh')
    step('remember to run mosh/install')

    # nodejs

    heading('nodejs')
    relink('.dotfiles/nodejs/npmrc', '~/.npmrc')
    step('remember to run nodejs/install')

    # pandoc

    heading('pandoc')
    step('remember to run pandoc/install')

    # pip

    heading('pip')
    mkdir('~/.config/pip')
    relink('~/.dotfiles/pip/pip.conf', '~/.config/pip/pip.conf')

    # pyenv

    heading('pyenv & pyenv-virtualenv')
    relink('~/.dotfiles/_lib/pyenv-virtualenv',
           '~/.dotfiles/_lib/pyenv/plugins/pyenv-virtualenv')

    # readline

    heading('readline')
    relink('.dotfiles/readline/inputrc', '~/.inputrc')

    # spacemacs

    heading('spacemacs')
    relink('.dotfiles/_lib/spacemacs', '~/.emacs.d')
    relink('.dotfiles/spacemacs/spacemacs', '~/.spacemacs')

    # ssh

    heading('ssh')
    relink('~/.dotfiles/ssh/config', '~/.ssh/config')

    # sshrc

    heading('sshrc')
    relink('.dotfiles/sshrc', '~/.sshrc.d')
    relink('.dotfiles/sshrc/sshrc', '~/.sshrc')

    # stack

    heading('stack')
    mkdir('~/.stack')
    unlink('~/.stack/config.yaml')
    step('remember to run stack/install')

    # tarsnap

    heading('tarsnap')
    step('remember to run tarsnap/install')

    # tmux

    heading('tmux')
    relink('.dotfiles/tmux/tmux.conf', '~/.tmux.conf')
    step('remember to run tmux/install')

    # vim

    heading('vim')
    relink('.dotfiles/vim/vimrc', '~/.vimrc')
    step('remember to run vim/install')

    # x11

    heading('x11')
    relink('.dotfiles/x11/Xresources', '~/.Xresources')
    relink('.dotfiles/x11/xinitrc', '~/.xinitrc')
    relink('.dotfiles/x11/xscreensaver', '~/.xscreensaver')
    step('remember to run x11/install (installs multiple utils)')

    # zsh

    heading('zsh')
    relink('.dotfiles/zsh/zshrc', '~/.zshrc')

    # _sites/current

    heading('_sites/current')
    p = os.path.expanduser('~/.dotfiles/_sites/current/_bin/dotfiles-install-site')
    if os.path.exists(p):
        step('running site-specific dotfiles-install-site')
        run(p)
    else:
        step('no site-specific dotfiles-install-site')

if __name__ == '__main__':
    sys.exit(main())

