#!/usr/bin/env python3
# vim: et sw=4 ts=4:

from __future__ import print_function

import os
import subprocess
import sys

def heading(s):
    print('\033[31m[*] %s\033[0m' % s)

def step(s):
    print('\033[33m[+] %s\033[0m' % s)

def relink(target, linkname):
    target = os.path.expanduser(target)
    linkname = os.path.expanduser(linkname)
    if os.path.exists(linkname):
        if os.path.islink(linkname):
            os.unlink(linkname)
        else:
            raise Exception('%s is not a symlink' % linkname)
    os.symlink(target, linkname)

def unlink(p):
    try:
        os.unlink(os.path.expanuser(p))
    except:
        pass

def mkdir(p):
    try:
        os.makedirs(os.path.expanduser(p))
    except:
        pass

def run(p):
    try:
        subprocess.check_call(p, shell=True)
    except:
        raise

def main():
    # <top level mkdirs>

    heading('<dirs>')
    mkdir('~/.config')
    mkdir('~/.fonts')
    mkdir('~/.root')

    # <fonts>

    heading('<fonts>')
    mkdir('~/.fonts/adobe-fonts')
    relink('~/.dotfiles/_lib/source-code-pro', '~/.fonts/adobe-fonts/source-code-pro')
    os.system('fc-cache -f -v ~/.fonts/adobe-fonts/source-code-pro > /dev/null 2>&1')

    # alpine

    heading('alpine')
    step('(optional) remember to run alpine/install')

    # ansifilter

    heading('ansifilter')
    step('(optional) remember to run ansifilter/install')

    # bash

    heading('bash')
    relink('.dotfiles/bash/bashrc', '~/.bashrc')
    relink('.dotfiles/bash/bash_profile', '~/.bash_profile')

    # bitwise

    heading('bitwise')
    step('(optional) remember to run bitwise/install')

    # bup

    heading('bup')
    step('(optional) remember to run bup/install')

    # cmake

    heading('cmake')
    step('(optional) remember to run cmake/install')

    # compton

    heading('compton / picom')
    step('(optional) remember to run compton/install or install from binary')

    # emacs

    heading('emacs')
    step('remember to run emacs/install-* (pick one) or install from binary')
    step('<sometimes, emacs pdumper needs cmake and poppler installed>')

    # flake8

    heading('flake8')
    relink('~/.dotfiles/flake8/flake8', '~/.config/flake8')

    # fzf

    heading('fzf')
    step('remember to run fzf/install or install from binary')

    # gdb

    heading('gdb')
    relink('.dotfiles/gdb/gdbinit', '~/.gdbinit')

    # git

    heading('git')
    relink('.dotfiles/git/gitconfig', '~/.gitconfig')
    step('(optional) remember to run git/install (for git-appraise)')

    # global

    heading('global')
    step('remember to run global/install or install from binary')

    # gnome

    heading('gnome')
    step('remember to run gnome/load')

    # i3

    heading('i3')
    relink('.dotfiles/i3', '~/.i3')
    relink('.dotfiles/i3/i3blocks.conf', '~/.i3blocks.conf')
    # TODO i3lock systemd

    # iftop

    heading('iftop')
    relink('.dotfiles/iftop/iftoprc', '~/.iftoprc')

    # less

    heading('less')
    # ... sourced in _shell/shellinteractive

    # maven

    heading('maven')
    step('(optional) remember to run maven/install')

    # mosh

    heading('mosh')
    step('(optional) remember to run mosh/install or install from binary')

    # nodejs

    heading('nodejs')
    relink('.dotfiles/nodejs/npmrc', '~/.npmrc')
    step('remember to run nodejs/install')

    # pandoc

    heading('pandoc')
    step('(optional) remember to run pandoc/install or install from binary')

    # poppler

    heading('poppler')
    step('(optional) remember to run poppler/install or install from binary')

    # pip

    heading('pip')
    mkdir('~/.config/pip')
    relink('~/.dotfiles/pip/pip.conf', '~/.config/pip/pip.conf')

    # pyenv

    heading('pyenv & pyenv-virtualenv')
    relink('~/.dotfiles/_lib/pyenv-virtualenv',
           '~/.dotfiles/_lib/pyenv/plugins/pyenv-virtualenv')

    # readline

    heading('readline')
    relink('.dotfiles/readline/inputrc', '~/.inputrc')

    # spacemacs

    heading('spacemacs')
    relink('.dotfiles/_lib/spacemacs', '~/.emacs.d')
    relink('.dotfiles/spacemacs/spacemacs', '~/.spacemacs')

    # ssh

    heading('ssh')
    relink('~/.dotfiles/ssh/config', '~/.ssh/config')

    # stack

    heading('stack')
    mkdir('~/.stack')
    unlink('~/.stack/config.yaml')
    step('(optional) remember to run stack/install or install from binary')

    # tarsnap

    heading('tarsnap')
    step('(optional) remember to run tarsnap/install')

    # tmux

    heading('tmux')
    relink('.dotfiles/tmux/tmux.conf', '~/.tmux.conf')
    step('remember to run tmux/install or install from binary')

    # wmctrl

    heading('wmctrl')
    step('(optional) remember to run wmctrl/install or install from binary')

    # vim

    heading('vim')
    relink('.dotfiles/vim/vimrc', '~/.vimrc')
    step('remember to run vim/install or install from binary')

    # x11

    heading('x11')
    relink('.dotfiles/_x11/Xresources', '~/.Xresources')
    relink('.dotfiles/_x11/xinitrc', '~/.xinitrc')
    relink('.dotfiles/_x11/xscreensaver', '~/.xscreensaver')

    # xclip

    heading('xclip')
    step('remember to run xclip/install or install from binary')

    # xdotool

    heading('xdotool')
    step('(optional) remember to run xdotool/install or install from binary')

    # zsh

    heading('zsh')
    relink('.dotfiles/zsh/zshrc', '~/.zshrc')

    # _sites/current

    heading('_sites/current')
    p = os.path.expanduser('~/.dotfiles/_sites/current/_bin/dotfiles-install-site')
    if os.path.exists(p):
        step('running site-specific dotfiles-install-site')
        run(p)
    else:
        step('no site-specific dotfiles-install-site')

if __name__ == '__main__':
    sys.exit(main())

