#!/usr/bin/env bash

git submodule sync --recursive
git submodule foreach --recursive 'branch="$(git config -f "$toplevel/.gitmodules" submodule.$name.branch)"; echo $branch; git checkout $branch'
git submodule update --recursive --init --rebase

