#!/usr/bin/env bash
# vim: et sw=4 ts=4:

set -e
set -u
set -x

if [[ $# = 0 || $1 == local ]]; then
    prefix=refs/heads/
    bindcmd='enter:execute(git checkout {1})+abort'
else
    prefix=refs/remotes/$1/
    bindcmd='enter:execute(git checkout -b $(echo {1} | cut -d '/' -f 2-) {1})+abort'
fi

git \
  for-each-ref \
  --count=1000 \
  --sort=-committerdate \
  --format='%(refname:short)' \
  $prefix | \
fzf \
  --preview="git log --color --pretty=fuller --decorate {1}" \
  --preview-window='up:75%:wrap' \
  --bind="$bindcmd"

