#!/usr/bin/env bash

set -e
set -u

echo '# git status'

git status --porcelain --ignored

echo '# git stash list'

git stash list | cat

echo '# git worktree list'

git worktree list | cat

echo '# git remote -v'

git remote -v

echo '# git branch'

# TODO what I really want to find is branches that have no remote or
# branches that are out of sync from the remote

git branch -vv | cat

echo '# git submodules isclean'

git submodule foreach --recursive git isclean

