#!/usr/bin/env bash
# vim: et sw=4 ts=4:

set -e
set -u
set -o pipefail

read -s password

hash=$(\
    echo -n "$password" | \
    sha1sum | \
    awk '{print $1}' | \
    tr '[:lower:]' '[:upper:]')

password=""

hit=$(\
    curl -v -s --stderr - https://api.pwnedpasswords.com/range/${hash:0:5} | \
    grep "${hash:5:35}" | \
    tr -d $'\r')

if [ -n "$hit" ]; then
    times=$(echo "$hit" | cut -d ':' -f 2)
    echo "seen $times times" >&2
    exit 1
fi

exit 0
