#!/usr/bin/env bash

set -e
set -u
set -o pipefail

strings $1/Info.plist | \
    grep '<date>' | \
    sed 's/.*>\(.*\)<.*/\1/g' | \
    tr -d -- '-' | \
    sed 's/\(.*\):..Z/\1Z/g' | \
    tr -d ':'

