#!/usr/bin/env python
# vim: set et sw=4 ts=4:

# TODO make this work on FreeBSD

import argparse
from math import ceil
import subprocess
import sys

import x_usage

command = "cat /proc/meminfo | grep MemAvailable | awk '{ print $2 }'; cat /proc/meminfo | grep MemTotal | awk '{ print $2 }'"

args = x_usage.parse_args()

returncode, stdout, stderr = x_usage.exec_command(args, command)

avail_kb, total_kb = [int(x.strip()) for x in stdout.splitlines()]
avail_gb = avail_kb / 1048576.0
total_gb = total_kb / 1048576.0
used_gb = total_gb - avail_gb
used_percent = (used_gb / total_gb) * 100

x_usage.output(args,
               format_string_default='{used_gb:.2f} / {total_gb:.2f} GB ({used_percent:.2f})%',
               format_string_i3='{used_percent:.2f}%',
               used_percent=used_percent,
               used_gb=used_gb,
               total_gb=total_gb)

