#!/usr/bin/env bash

set -e
set -u
set -o pipefail

TR=$(command -v gtr &> /dev/null && echo gtr || echo tr)

len=${1:-32}
valid=${2:-"[:graph:]"}

echo $($TR -dc "$valid" < /dev/urandom | head -c${1:-$len})
