#!/usr/bin/env python

import subprocess
import sys

output = subprocess.check_output(['ssh', '-V'], stderr=subprocess.STDOUT)
if not output.startswith('OpenSSH_'):
    raise ValueError('do not know how to handle this version string')
parts = output.split(' ')
parts = parts[0].split('_')
assert parts[0] == 'OpenSSH'
if 'p' in parts[1]:
    number, patch = parts[1].split('p')
    can_include = float(number) >= 7.3 and int(patch) >= 1
else:
    can_include = float(number) >= 7.4
sys.exit(0 if can_include else 1)
