#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

pushd .
cd $(dirname $0)
cd ../_lib/compton
git reset --hard
git clean -fdx
export PREFIX=$HOME/.local
make clean
make
make docs
make install
popd

