#!/usr/bin/env bash

# TODO this only works on linux

set -e
set -u
set -x
set -o pipefail

TMPDIR=$(mktemp -d)

cd $TMPDIR

cleanup () {
    rm -rf $TMPDIR
}

trap cleanup EXIT

wget https://www.stackage.org/stack/linux-x86_64 -O stack.tar.gz
tar -xzf stack.tar.gz
name="$(find . -type d -name 'stack-*' | cut -d '/' -f 2)"
mkdir -p ~/.local/var
mv "$name" ~/.local/var/
ln -sf "../../.local/var/$name/stack" ~/.dotfiles/_bin/stack
rm -f stack.tar.gz
stack setup

