#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

pushd .
cd $(dirname $0)

MANDIR=~/.root/share/man/man1
mkdir -p $MANDIR

cd ../_lib/fzf
git reset --hard
git clean -fdx

if [[ "$(uname -m)" == i686 ]]; then
	echo "WARNING: fzf builds stopped supporting i686 at 0.22.0" >&2
	git checkout 0.22.0
fi

ln -sf ~/.dotfiles/_lib/fzf ~/.fzf
cd ~/.fzf
bash -x ./install --key-bindings --completion --no-update-rc --no-fish
rm -f $MANDIR/fzf.1 $MANDIR/fzf-tmux.1
ln -sf ~/.dotfiles/_lib/fzf/man/man1/fzf.1 $MANDIR/
ln -sf ~/.dotfiles/_lib/fzf/man/man1/fzf-tmux.1 $MANDIR/

popd

