#!/usr/bin/env bash

asdf plugin add awscli https://github.com/MetricMike/asdf-awscli.git
asdf plugin add direnv https://github.com/asdf-community/asdf-direnv.git
asdf plugin add perl https://github.com/ouest/asdf-perl.git
asdf plugin add poetry https://github.com/asdf-community/asdf-poetry.git
asdf plugin add pre-commit https://github.com/jonathanmorley/asdf-pre-commit.git
asdf plugin add python https://github.com/danhper/asdf-python.git
asdf plugin add terraform-docs https://github.com/looztra/asdf-terraform-docs.git
asdf plugin add terraform https://github.com/Banno/asdf-hashicorp.git
asdf plugin add terraformer https://github.com/grimoh/asdf-terraformer.git
asdf plugin add terragrunt https://github.com/ohmer/asdf-terragrunt.git
asdf plugin add tflint https://github.com/skyzyx/asdf-tflint
asdf plugin add tfupdate https://github.com/yuokada/asdf-tfupdate.git
asdf install

