#!/usr/bin/env bash

set -e
set -u

pushd . &> /dev/null
cd "$(dirname "$0")"
diff -u \
     <(dconf dump /org/gnome/terminal/) \
     gnome-terminal.dconf &> /dev/null || \
    echo "gnome-terminal.dconf difference!"
dconf load /org/gnome/terminal/ < gnome-terminal.dconf
popd &> /dev/null
