#!/usr/bin/env bash

set -e
set -u

pushd . &> /dev/null
cd $(dirname $0)
diff -u \
     <(gconftool-2 --dump /apps/gnome-terminal) \
     gnomeconfig.xml &> /dev/null || \
    echo "gnomeconfig.xml difference!"
gconftool-2 --load gnomeconfig.xml
popd &> /dev/null

