#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

pushd .
cd $(dirname $0)
cd ../_lib/_opt/tarsnap
git reset --hard
git clean -fdx
[ ! -f ./configure ] && {
    autoreconf -i
    # libtoolize --force
    # aclocal
    # autoheader
    # automake --force-missing --add-missing
    # autoconf
}
./configure --prefix ~/.root
make && make install
popd

