return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    delay = 300,
    icons = {
      mappings = false,
    },
    preset = "modern",
    triggers = {
      { "<auto>", mode = "nxso" },
      { "<localleader>", mode = { "n", "x" } },
    },
    spec = {
      { "<leader><tab>", desc = "alternate buffer" },
      { "<leader>b", group = "buffers" },
      { "<leader>c", group = "code" },
      { "<leader>d", group = "debug" },
      { "<leader>e", group = "errors" },
      { "<leader>f", group = "files" },
      { "<leader>fe", group = "config" },
      { "<leader>g", group = "git" },
      { "<leader>h", group = "help" },
      { "<leader>j", group = "jump" },
      { "<leader>m", group = "multicursor" },
      { "<leader>o", group = "open" },
      { "<leader>p", group = "project" },
      { "<leader>q", group = "quit/session" },
      { "<leader>r", group = "run" },
      { "<leader>s", group = "search" },
      { "<leader>t", group = "toggle" },
      { "<leader>ta", desc = "toggle auto-completion mode" },
      { "<leader>tA", desc = "toggle completion for buffer" },
      { "<leader>tC", desc = "cycle completion mode" },
      { "<leader>th", desc = "toggle signature auto-popup" },
      { "<leader>tR", desc = "toggle inc-rename live preview" },
      { "<leader>tv", group = "view/listchars" },
      { "<leader>w", group = "windows" },
      { "<leader>y", group = "clipboard" },
      { "<localleader>", group = "local" },
      { "<localleader>a", group = "action", mode = { "n", "x" } },
      { "<localleader>F", group = "folder" },
      { "<localleader>b", group = "backend" },
      { "<localleader>c", group = "compile" },
      { "<localleader>d", group = "debug" },
      { "<localleader>e", group = "errors/exec" },
      { "<localleader>f", group = "flow/calls" },
      { "<localleader>g", group = "goto" },
      { "<localleader>h", group = "help" },
      { "<localleader>i", group = "insert/import" },
      { "<localleader>q", group = "workspace" },
      { "<localleader>r", group = "refactor" },
      { "<localleader>t", group = "test" },
      { "<localleader>T", group = "toggle" },
      { "<localleader>x", group = "execute" },
      { "<localleader>=", group = "format" },
    },
    win = {
      border = "rounded",
    },
  },
}
