return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    delay = 300,
    icons = {
      -- which-key draws special key names as Nerd Font pictograms, and 24 of
      -- the 28 sit in the Material Design Icons block (U+F0000 and up) that
      -- Nerd Fonts only added in v3, so on an older patched font <Space>,
      -- <Tab>, <Esc>, <BS> and every modifier come out as tofu -- which is why
      -- "alternate buffer", "Commands", "close" and which-key's own "back"
      -- looked broken. Spell them out instead: font-proof, and it matches the
      -- SPC / TAB / C- notation the README already uses. Word-style names carry
      -- a trailing space because view.format concatenates keys with no
      -- separator; modifier prefixes must not.
      keys = {
        BS = "BS ",
        C = "C-",
        CR = "RET ",
        D = "D-",
        Down = "Down ",
        Esc = "ESC ",
        F1 = "F1 ",
        F2 = "F2 ",
        F3 = "F3 ",
        F4 = "F4 ",
        F5 = "F5 ",
        F6 = "F6 ",
        F7 = "F7 ",
        F8 = "F8 ",
        F9 = "F9 ",
        F10 = "F10 ",
        F11 = "F11 ",
        F12 = "F12 ",
        Left = "Left ",
        M = "M-",
        Right = "Right ",
        S = "S-",
        ScrollWheelDown = "WheelDown ",
        ScrollWheelUp = "WheelUp ",
        Space = "SPC ",
        Tab = "TAB ",
        Up = "Up ",
      },
      mappings = false,
    },
    preset = "modern",
    triggers = {
      { "<auto>", mode = "nxso" },
      { "<localleader>", mode = { "n", "x" } },
    },
    spec = {
      { "<leader><tab>", desc = "alternate buffer" },
      { "<leader>b", group = "buffers" },
      { "<leader>c", group = "code" },
      { "<leader>d", group = "debug" },
      { "<leader>e", group = "errors" },
      { "<leader>f", group = "files" },
      { "<leader>fe", group = "config" },
      { "<leader>g", group = "git" },
      { "<leader>gl", desc = "blame file (reblame r/R)" },
      { "<leader>gL", desc = "log line history (git log -L)", mode = { "n", "x" } },
      { "<leader>h", group = "help" },
      { "<leader>j", group = "jump" },
      { "<leader>m", group = "multicursor" },
      { "<leader>o", group = "open" },
      { "<leader>p", group = "project" },
      { "<leader>q", group = "quit/session" },
      { "<leader>r", group = "run" },
      { "<leader>s", group = "search" },
      { "<leader>t", group = "toggle" },
      { "<leader>ta", desc = "toggle auto-completion mode" },
      { "<leader>tA", desc = "auto-completion: toggle for buffer" },
      { "<leader>tM", desc = "auto-completion: cycle mode" },
      { "<leader>tC", desc = "cycle clipboard mode (full/tmux/off)" },
      { "<leader>tX", desc = "toggle clipboard off ↔ full" },
      { "<leader>th", desc = "toggle signature auto-popup" },
      { "<leader>tR", desc = "toggle inc-rename live preview" },
      { "<leader>tv", group = "view/listchars" },
      { "<leader>w", group = "windows" },
      { "<leader>y", group = "clipboard" },
      { "<localleader>", group = "local" },
      { "<localleader>a", group = "action", mode = { "n", "x" } },
      { "<localleader>F", group = "folder" },
      { "<localleader>b", group = "backend" },
      { "<localleader>c", group = "compile" },
      { "<localleader>d", group = "debug" },
      { "<localleader>e", group = "errors/exec" },
      { "<localleader>f", group = "flow/calls" },
      { "<localleader>g", group = "goto" },
      { "<localleader>h", group = "help" },
      { "<localleader>i", group = "insert/import" },
      { "<localleader>q", group = "workspace" },
      { "<localleader>r", group = "refactor" },
      { "<localleader>t", group = "test" },
      { "<localleader>T", group = "toggle" },
      { "<localleader>x", group = "execute" },
      { "<localleader>=", group = "format" },
    },
    win = {
      border = "rounded",
    },
  },
}
