return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    delay = 300,
    icons = {
      mappings = false,
    },
    preset = "modern",
    triggers = {
      { "<auto>", mode = "nxso" },
      { "<localleader>", mode = { "n", "x" } },
    },
    spec = {
      { "<leader><tab>", desc = "alternate buffer" },
      { "<leader>b", group = "buffers" },
      { "<leader>c", group = "code" },
      { "<leader>e", group = "edit" },
      { "<leader>f", group = "files" },
      { "<leader>fe", group = "config" },
      { "<leader>g", group = "git" },
      { "<leader>j", group = "jump" },
      { "<leader>o", group = "open" },
      { "<leader>p", group = "project" },
      { "<leader>q", group = "quit/session" },
      { "<leader>r", group = "run" },
      { "<leader>s", group = "search" },
      { "<leader>t", group = "toggle" },
      { "<leader>tv", group = "view/listchars" },
      { "<leader>w", group = "windows" },
      { "<leader>y", group = "clipboard" },
      { "<localleader>", group = "local" },
      { "<localleader>a", group = "action", mode = { "n", "x" } },
      { "<localleader>g", group = "goto" },
      { "<localleader>h", group = "help" },
      { "<localleader>r", group = "refactor" },
      { "<localleader>=", group = "format" },
    },
    win = {
      border = "rounded",
    },
  },
}
