#!/usr/bin/env bash

set -e
set -u
set -x

pushd .
cd $(dirname $0)
cd ../_lib/tmux
git reset --hard
git clean -fdx
[ ! -f ./configure ] && sh autogen.sh
./configure --prefix ~/.root
make && make install
popd

