#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

pushd .
cd $(dirname $0)
cd ../_lib/_opt/tmux
git reset --hard
git clean -fdx
[ ! -f ./configure ] && sh autogen.sh
./configure --prefix ~/.local
make && make install
popd

