#!/bin/bash

set -e
set -u
set -x

VERSION=25.3

wget https://ftp.gnu.org/pub/gnu/emacs/emacs-${VERSION}.tar.gz
tar -xzvf emacs-${VERSION}.tar.gz
cd emacs-${VERSION}
./configure --prefix ~/.root
make && make install
cd ..
rm -rf emacs-${VERSION}.tar.gz emacs-${VERSION}

