#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

TMPDIR=$(mktemp -d)

cd $TMPDIR

cleanup () {
    rm -rf $TMPDIR
}

trap cleanup EXIT

VERSION=25.3

wget https://ftp.gnu.org/pub/gnu/emacs/emacs-${VERSION}.tar.gz
tar -xzvf emacs-${VERSION}.tar.gz
cd emacs-${VERSION}
./configure --prefix ~/.root
make && make install

