#!/usr/bin/env bash

set -e
set -u
set -x
set -o pipefail

TMPDIR=$(mktemp -d)

cd $TMPDIR

cleanup () {
    rm -rf $TMPDIR
}

trap cleanup EXIT

VERSION=29.4

wget https://ftp.gnu.org/pub/gnu/emacs/emacs-${VERSION}.tar.gz
tar -xzvf emacs-${VERSION}.tar.gz
cd emacs-${VERSION}

# other interesting options:
#
# --with-json
# --with-mailutils
# --with-native-compilation
# --with-pgtk
# --with-tree-sitter
# --with-xwidgets
#
# --with-pgtk might be necessary for emacs on WSL

./configure \
    --prefix ~/.root

make -j4 && make install

